-- ==========================================
-- LIMPIEZA DE TABLAS ANTERIORES (Opcional)
-- Esto borrará las tablas del primer script y cualquier tabla existente para empezar limpio
-- ==========================================
DROP TABLE IF EXISTS public.cloud_saves CASCADE;
DROP TABLE IF EXISTS public.leaderboard CASCADE;

DROP TABLE IF EXISTS public.telemetria_eventos CASCADE;
DROP TABLE IF EXISTS public.sesiones CASCADE;
DROP TABLE IF EXISTS public.protocolo_maestro CASCADE;
DROP TABLE IF EXISTS public.escenarios CASCADE;
DROP TABLE IF EXISTS public.usuarios CASCADE;

-- 1. Crear tabla Usuarios (Conectada al sistema de Auth de Supabase)
CREATE TABLE public.usuarios (
    id_usuario UUID PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
    nombre TEXT NOT NULL,
    carrera TEXT,
    fecha_registro TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now())
);

-- 2. Crear tabla Escenarios (Niveles del juego)
CREATE TABLE public.escenarios (
    id_escenario BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre TEXT NOT NULL,
    nivel_dificultad INTEGER CHECK (nivel_dificultad BETWEEN 1 AND 5),
    tiempo_base_seg INTEGER
);

-- 3. Crear tabla Protocolo_Maestro (Pasos correctos a seguir)
CREATE TABLE public.protocolo_maestro (
    id_paso BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_escenario BIGINT NOT NULL REFERENCES public.escenarios(id_escenario) ON DELETE CASCADE,
    orden_logico INTEGER NOT NULL,
    descripcion TEXT NOT NULL,
    penalizacion_tiempo REAL DEFAULT 0
);

-- 4. Crear tabla Sesiones (Intentos de los jugadores)
CREATE TABLE public.sesiones (
    id_sesion BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_usuario UUID NOT NULL REFERENCES public.usuarios(id_usuario) ON DELETE CASCADE,
    id_escenario BIGINT NOT NULL REFERENCES public.escenarios(id_escenario) ON DELETE CASCADE,
    fecha_hora TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()),
    puntaje_final INTEGER,
    resultado TEXT CHECK (resultado IN ('Salvado', 'Fallecido'))
);

-- 5. Crear tabla Telemetria_Eventos (Acciones realizadas durante la sesión)
CREATE TABLE public.telemetria_eventos (
    id_evento BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_sesion BIGINT NOT NULL REFERENCES public.sesiones(id_sesion) ON DELETE CASCADE,
    accion_realizada TEXT NOT NULL,
    es_correcto BOOLEAN NOT NULL,
    tiempo_seg REAL NOT NULL,
    estado_salud_momento TEXT
);


----------------------------------------------------------------------------------
-- SEGURIDAD (Row Level Security - RLS)
-- Para evitar que jugadores modifiquen los datos de otros o hagan trampas
----------------------------------------------------------------------------------

ALTER TABLE public.usuarios ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.escenarios ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.protocolo_maestro ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.sesiones ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.telemetria_eventos ENABLE ROW LEVEL SECURITY;

-- USUARIOS: Un jugador solo puede ver y editar su propio perfil
CREATE POLICY "Usuarios gestionan su perfil" ON public.usuarios 
    FOR ALL USING (auth.uid() = id_usuario) WITH CHECK (auth.uid() = id_usuario);

-- ESCENARIOS y PROTOCOLOS: Todo el mundo puede LEERLOS, pero solo un admin (desde el panel web) puede CREARLOS
CREATE POLICY "Lectura pública de escenarios" ON public.escenarios FOR SELECT USING (true);
CREATE POLICY "Lectura pública de protocolos" ON public.protocolo_maestro FOR SELECT USING (true);

-- SESIONES: Un jugador solo puede crear y ver sus propias sesiones jugadas
CREATE POLICY "Jugadores gestionan sus sesiones" ON public.sesiones 
    FOR ALL USING (auth.uid() = id_usuario) WITH CHECK (auth.uid() = id_usuario);

-- TELEMETRIA: Un jugador solo puede enviar eventos a sus propias sesiones
CREATE POLICY "Jugadores registran su telemetria" ON public.telemetria_eventos 
    FOR ALL USING (
        EXISTS (SELECT 1 FROM public.sesiones s WHERE s.id_sesion = telemetria_eventos.id_sesion AND s.id_usuario = auth.uid())
    ) 
    WITH CHECK (
        EXISTS (SELECT 1 FROM public.sesiones s WHERE s.id_sesion = telemetria_eventos.id_sesion AND s.id_usuario = auth.uid())
    );


----------------------------------------------------------------------------------
-- TRIGGERS Y FUNCIONES (Lógica de Negocio en Base de Datos)
----------------------------------------------------------------------------------

-- 1. Validar puntaje negativo (Equivalente a los primeros 2 triggers en PostgreSQL)
-- Nota: En PostgreSQL es más eficiente usar un constraint CHECK, pero aquí usamos 
-- un trigger para mantener tus mensajes de error personalizados.
CREATE OR REPLACE FUNCTION public.validar_puntaje_negativo_fn()
RETURNS TRIGGER AS $$
BEGIN
    IF NEW.puntaje_final < 0 THEN
        RAISE EXCEPTION 'Error de Juego: El puntaje final no puede ser negativo.';
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS trg_validar_puntaje_negativo ON public.sesiones;
CREATE TRIGGER trg_validar_puntaje_negativo
BEFORE INSERT OR UPDATE OF puntaje_final ON public.sesiones
FOR EACH ROW
EXECUTE FUNCTION public.validar_puntaje_negativo_fn();


-- 2. Validar que la sesión no cierre sin eventos
CREATE OR REPLACE FUNCTION public.validar_eventos_al_cerrar_fn()
RETURNS TRIGGER AS $$
BEGIN
    IF NEW.resultado IS NOT NULL THEN
        IF (SELECT COUNT(*) FROM public.telemetria_eventos WHERE id_sesion = NEW.id_sesion) = 0 THEN
            RAISE EXCEPTION 'No se puede finalizar sesión sin eventos de telemetría';
        END IF;
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS trg_validar_eventos_al_cerrar ON public.sesiones;
CREATE TRIGGER trg_validar_eventos_al_cerrar
BEFORE UPDATE ON public.sesiones
FOR EACH ROW
EXECUTE FUNCTION public.validar_eventos_al_cerrar_fn();


-- 3. Actualizar el puntaje final automáticamente al equivocarse
CREATE OR REPLACE FUNCTION public.actualizar_puntaje_final_fn()
RETURNS TRIGGER AS $$
BEGIN
    IF NEW.es_correcto = false THEN
        UPDATE public.sesiones
        SET puntaje_final = COALESCE(puntaje_final, 100) - 10
        WHERE id_sesion = NEW.id_sesion;
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS trg_actualizar_puntaje_final ON public.telemetria_eventos;
CREATE TRIGGER trg_actualizar_puntaje_final
AFTER INSERT ON public.telemetria_eventos
FOR EACH ROW
EXECUTE FUNCTION public.actualizar_puntaje_final_fn();
